import { golos } from '@/shared/fonts'

import type { Metadata } from 'next'

import '@/shared/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${golos.className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
